"use strict";

const TARGET_STARS = 10;
const categories = [
  {id:"jiran",icon:"🏠",name:"Jiran"},
  {id:"sekolah",icon:"🏫",name:"Sekolah"},
  {id:"taman",icon:"🛝",name:"Taman Permainan"},
  {id:"majlis",icon:"🎉",name:"Majlis"},
  {id:"dewan",icon:"🏢",name:"Dewan Komuniti"},
  {id:"pendapat",icon:"💬",name:"Perbezaan Pendapat"},
  {id:"kbat",icon:"🔥",name:"Cabaran KBAT"}
];

const data = {
jiran:[
{s:"Jiran sebelah mengadakan majlis hari lahir. Bunyi muzik agak kuat. Seorang jiran terus marah dan mahu membuat aduan tanpa berbincang.",q:"Apakah tindakan yang lebih bertoleransi?",o:["😡 Terus memarahi jiran","🤝 Berbincang dengan sopan","📢 Membuat bising semula"],a:1,f:"Hebat! Kita perlu berbincang dengan baik sebelum mengambil tindakan.",extra:"Bagaimanakah perasaan jiran jika ditegur dengan sopan?",answer:"Jiran mungkin berasa dihormati, tenang dan lebih bersedia untuk berbincang."},
{s:"Jiran mahu meletakkan kereta di hadapan rumah untuk sementara kerana mempunyai tetamu.",q:"Apakah tindakan yang paling sesuai?",o:["Terus bergaduh","Berbincang dan mencari penyelesaian","Menghalang kereta jiran"],a:1,f:"Bagus! Perbincangan membantu kedua-dua pihak mencari jalan yang adil.",answer:"Berbincang dan mencari penyelesaian yang dipersetujui bersama."},
{s:"Anak jiran bermain bola dan bola tersebut masuk ke halaman rumah kamu.",q:"Apakah tindakan yang menunjukkan toleransi?",o:["Menyimpan bola tersebut","Memulangkan bola dengan baik","Memarahi mereka"],a:1,f:"Tepat! Memulangkan bola dengan baik menunjukkan sikap bertoleransi.",answer:"Memulangkan bola dengan baik dan mengingatkan mereka secara sopan."}
],
sekolah:[
{s:"Dua orang murid mahu menggunakan komputer yang sama untuk menyiapkan tugasan.",q:"Apakah penyelesaian yang adil?",o:["Berebut komputer","Bergilir-gilir menggunakan komputer","Tidak membenarkan sesiapa menggunakannya"],a:1,f:"Bagus! Bergilir-gilir ialah penyelesaian adil.",extra:"Apa akan berlaku jika kedua-duanya terus berebut?",answer:"Mereka mungkin bergaduh, tugasan terganggu dan hubungan menjadi kurang baik."},
{s:"Dua kumpulan mahu menggunakan ruang bacaan pada masa yang sama.",q:"Apakah tindakan bertoleransi?",open:true,answer:"Berbincang dan membahagikan masa penggunaan ruang."},
{s:"Rakan kamu mempunyai pendapat yang berbeza semasa aktiviti kumpulan.",q:"Apakah tindakan yang paling baik?",o:["Mengejek pendapatnya","Mendengar pendapatnya terlebih dahulu","Memaksanya menerima pendapat kamu"],a:1,f:"Tepat! Mendengar dahulu menunjukkan kita menghormati rakan.",answer:"Mendengar pendapatnya terlebih dahulu dan berbincang dengan baik."}
],
taman:[
{s:"Sekumpulan kanak-kanak sedang menggunakan buaian. Seorang murid baru datang dan mahu menggunakan buaian dengan segera.",q:"Apakah sikap toleransi yang boleh diamalkan?",o:["Berebut","Menunggu giliran","Menolak rakan"],a:1,f:"Hebat! Menunggu giliran menunjukkan toleransi.",answer:"Menunggu giliran dan meminta dengan sopan."},
{s:"Dua kumpulan mahu menggunakan gelanggang yang sama.",q:"Bagaimanakah mereka boleh menyelesaikan masalah?",open:true,answer:"Membahagikan masa penggunaan gelanggang atau bergilir-gilir."},
{s:"Seorang kanak-kanak bermain lebih lama daripada orang lain.",q:"Apakah yang boleh kamu katakan dengan sopan?",open:true,frame:"Boleh kita ______ supaya semua orang mendapat giliran?",answer:"Contoh: Boleh kita bergilir-gilir supaya semua orang mendapat giliran?"}
],
majlis:[
{s:"Dalam satu majlis komuniti, terdapat makanan yang disukai oleh sesetengah orang tetapi tidak disukai oleh orang lain.",q:"Patutkah kita mengejek pilihan makanan orang lain?",o:["Ya","Tidak"],a:1,f:"Tepat! Kita perlu menghormati pilihan orang lain.",extra:"Mengapa kita perlu menghormati pilihan orang lain?",answer:"Kerana setiap orang mempunyai pilihan dan kesukaan yang berbeza."},
{s:"Seorang jiran tidak mahu menyertai permainan tertentu dalam majlis.",q:"Apakah tindakan yang paling bertoleransi?",o:["Memaksanya","Menghormati pilihannya","Mengejeknya"],a:1,f:"Bagus! Menghormati pilihan orang lain ialah toleransi.",answer:"Menghormati pilihannya dan tidak memaksa."},
{s:"Beberapa orang mempunyai cadangan aktiviti yang berbeza semasa majlis.",q:"Apakah yang boleh dilakukan?",open:true,answer:"Berbincang dan memilih aktiviti yang dipersetujui bersama."}
],
dewan:[
{s:"Dua kumpulan penduduk mahu menggunakan dewan komuniti pada waktu yang sama.",q:"Selesaikan cabaran empat tahap.",levels:[
["🔍 Tahap 1 – Kenal pasti","Apakah masalah yang berlaku?","Dua kumpulan mahu menggunakan dewan pada masa yang sama.",1],
["🤝 Tahap 2 – Tindakan","Apa yang patut mereka lakukan?","Berbincang dan membahagikan masa penggunaan dewan.",1],
["🔮 Tahap 3 – Ramalkan kesan","Apa akan berlaku jika mereka enggan bertoleransi?","Mereka mungkin bergaduh dan hubungan menjadi renggang.",1],
["🧠 Tahap 4 – Justifikasi","Mengapa tindakan bertoleransi lebih baik?","Kerana semua pihak dapat menggunakan dewan dengan adil dan masyarakat hidup aman.",2]],answer:"Berbincang, membahagikan masa dengan adil dan menghormati persetujuan bersama."},
{s:"Dua aktiviti komuniti dijadualkan pada tarikh yang sama.",q:"Cadangkan satu penyelesaian yang memberi manfaat kepada kedua-dua pihak.",open:true,answer:"Ubah masa salah satu aktiviti, bahagikan masa dewan, atau cari tempat alternatif melalui persetujuan bersama."},
{s:"Satu kumpulan mahu menggunakan dewan lebih lama daripada masa yang ditetapkan.",q:"Apakah tindakan yang adil kepada kumpulan lain?",o:["Terus guna sehingga selesai","Mengikut masa yang dipersetujui","Menghalang kumpulan lain masuk"],a:1,f:"Tepat! Menepati masa yang dipersetujui menghormati hak orang lain.",answer:"Mengikut masa yang dipersetujui."}
],
pendapat:[
{s:"Penduduk berbincang tentang warna baharu untuk mengecat pagar taman. Ada yang memilih biru dan ada yang memilih hijau.",q:"Adakah semua orang perlu mempunyai pendapat yang sama?",o:["Ya","Tidak"],a:1,f:"Betul! Kita boleh berbeza pendapat dan masih saling menghormati.",extra:"Bagaimanakah mereka boleh membuat keputusan tanpa bergaduh?",answer:"Berbincang, mengundi atau mencari persetujuan bersama."},
{s:"Dua murid mempunyai idea yang berbeza untuk menyiapkan projek.",q:"Apakah tindakan yang paling baik?",o:["Memaksa rakan menerima idea sendiri","Mendengar kedua-dua idea","Tidak bercakap dengan rakan"],a:1,f:"Bagus! Mendengar kedua-dua idea membantu membuat keputusan yang lebih adil.",answer:"Mendengar kedua-dua idea dan berbincang."},
{s:"Ahli kumpulan tidak bersetuju tentang pembahagian tugas.",q:"Apakah yang perlu dilakukan?",open:true,answer:"Berbincang dan membahagikan tugas secara adil."}
],
kbat:[
{s:"Apa akan berlaku jika semua orang dalam masyarakat tidak mahu bertolak ansur?",q:"Berikan ramalan dan sebab.",open:true,answer:"Konflik, pergaduhan dan hubungan renggang boleh berlaku kerana semua orang hanya mahu kehendak sendiri dipenuhi."},
{s:"Adakah bertoleransi bermaksud kita perlu bersetuju dengan semua perkara? Jelaskan.",q:"Berikan justifikasi.",open:true,answer:"Tidak. Kita boleh tidak bersetuju tetapi tetap mendengar, menghormati dan berbincang dengan sopan."},
{s:"Bagaimanakah toleransi boleh membantu menyelesaikan konflik?",q:"Terangkan hubungan antara toleransi dan penyelesaian konflik.",open:true,answer:"Toleransi membantu orang mendengar, bertolak ansur dan mencari penyelesaian yang adil."},
{s:"Jika kamu tidak bersetuju dengan rakan, bagaimana kamu boleh menunjukkan toleransi?",q:"Berikan tindakan dan alasan.",open:true,answer:"Dengar pendapat rakan, bercakap dengan sopan dan cari persetujuan bersama."},
{s:"Mengapa menghormati pendapat orang lain penting walaupun kita tidak bersetuju?",q:"Berikan justifikasi.",open:true,answer:"Kerana setiap orang berhak bersuara dan rasa dihormati membantu perbincangan kekal aman."},
{s:"Apakah yang mungkin berlaku kepada masyarakat jika penduduk sering bergaduh?",q:"Ramalkan sekurang-kurangnya dua kesan.",open:true,answer:"Masyarakat menjadi tidak aman, hubungan renggang dan kerjasama berkurang."},
{s:"Cadangkan dua cara untuk menyelesaikan perbezaan pendapat secara aman.",q:"Bandingkan dua cara.",open:true,answer:"Contohnya berbincang dan mengundi. Kedua-duanya boleh membantu membuat keputusan tanpa bergaduh."},
{s:"Mana lebih baik: menang dalam pertengkaran atau mencari penyelesaian bersama? Mengapa?",q:"Pilih dan berikan sebab.",open:true,answer:"Mencari penyelesaian bersama lebih baik kerana semua pihak dihormati dan hubungan kekal baik."}
]};

const app=document.getElementById("app"),statusBar=document.getElementById("statusBar"),toast=document.getElementById("toast");
let state={stars:0,rounds:0,mode:"normal",sound:true,lastCategory:null,played:[],answered:0,badges:[],screen:"home",currentCategory:null,currentIndex:0,rotation:0,answerVisible:false,levelDone:{}};
function load(){try{const s=JSON.parse(localStorage.getItem("roda-toleransi-v1"));if(s)state={...state,...s}}catch(e){}}
function save(){localStorage.setItem("roda-toleransi-v1",JSON.stringify(state));updateStatus()}
function showToast(msg){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2100)}
function beep(freq=760,d=.12){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=freq;g.gain.setValueAtTime(.045,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.start();o.stop(c.currentTime+d+.02);o.onended=()=>c.close()}catch(e){}}
function updateStatus(){document.getElementById("starCount").textContent=state.stars;document.getElementById("starTarget").textContent=TARGET_STARS;document.getElementById("roundCount").textContent=state.rounds;statusBar.classList.toggle("hidden",state.screen==="home")}
function render(html,screen){state.screen=screen;save();app.innerHTML='<section class="screen">'+html+"</section>";window.scrollTo({top:0,behavior:"smooth"})}
function modeButtons(){return '<div class="mode-row"><button class="secondary mode-btn '+(state.mode==="easy"?"active":"")+'" onclick="setMode(\'easy\')">🌱 MOD MUDAH</button><button class="secondary mode-btn '+(state.mode==="kbat"?"active":"")+'" onclick="setMode(\'kbat\')">🔥 MOD KBAT</button><button class="secondary mode-btn '+(state.mode==="normal"?"active":"")+'" onclick="setMode(\'normal\')">🎯 MOD BIASA</button></div>'}
function renderHome(){render('<div class="hero"><div><span class="pill">Pendidikan Moral Tahun 5</span><h1>🎡 RODA CABARAN TOLERANSI</h1><p class="subtitle">“Putar roda, selesaikan cabaran dan bina masyarakat harmoni!”</p><div class="meta"><span class="pill">🤝 Toleransi</span><span class="pill">❤️ Hormat</span><span class="pill">⭐ 10 Bintang</span></div><p>Kenal pasti masalah, pilih tindakan bertoleransi, jelaskan sebab, ramalkan kesan dan beri justifikasi.</p>'+modeButtons()+'<div class="action-row"><button class="primary" onclick="startGame()">▶️ MULA BERMAIN</button><button class="secondary" onclick="showHow()">📖 CARA BERMAIN</button></div></div><div class="hero-art"><div class="hero-wheel">🎡</div><div class="hero-neighborhood">🏠 🌳 🏡 🤝</div><div class="float f1">⭐</div><div class="float f2">❤️</div></div></div>',"home")}
function showHow(){render('<div class="panel"><h1>📖 Cara Bermain</h1><ol class="situation-text"><li>Putar roda.</li><li>Lihat kategori yang dipilih.</li><li>Baca situasi.</li><li>Jawab cabaran.</li><li>Kumpul ⭐ Bintang Toleransi.</li><li>Capai 10 bintang untuk menjadi 🏆 Pasukan Harmoni!</li></ol><div class="action-row"><button class="primary" onclick="startGame()">🎡 Mula</button><button class="secondary" onclick="renderHome()">← Kembali</button></div></div>',"how")}
function setMode(m){state.mode=m;save();if(state.screen==="home")renderHome();else if(state.screen==="wheel")renderWheel()}
function startGame(){renderWheel()}
function wheelLabels(){return categories.map((c,i)=>{const angle=i*(360/7)+25.7;const rad=(angle-90)*Math.PI/180;const x=50+32*Math.cos(rad),y=50+32*Math.sin(rad);return '<div class="wlabel" style="left:'+x+'%;top:'+y+'%;transform:translate(-50%,-50%) rotate('+(angle)+'deg)"><span style="display:block;transform:rotate('+(-angle)+'deg)">'+c.icon+'<br>'+c.name+'</span></div>'}).join("")}
function renderWheel(){render('<div class="wheel-layout"><div class="panel center"><div class="wheel-wrap"><div class="pointer">▼</div><div id="wheel" class="wheel" style="transform:rotate('+state.rotation+'deg)"></div><div class="wheel-labels">'+wheelLabels()+'</div><button id="spinBtn" class="spin-btn" onclick="spinWheel()">🎡 PUTAR<br>RODA!</button></div></div><div class="panel"><span class="pill">🎯 Pilih Cabaran</span><h1>Putar roda!</h1><p class="situation-text">Setiap pusingan memilih satu kategori secara rawak. Cuba kumpul <b>10 bintang</b> untuk menjadi Pasukan Harmoni.</p>'+modeButtons()+'<div id="selectedArea" class="selected-card"><div class="selected-icon">🤝</div><h2>Siap untuk cabaran?</h2><p>Tekan butang di tengah roda.</p></div><div class="action-row"><button class="secondary" onclick="speakText(\'Putar roda untuk memilih kategori cabaran toleransi.\')">🔊 BACA ARAHAN</button></div>'+renderBadges()+'</div></div>',"wheel")}
function chooseCategory(){let pool=categories.map((_,i)=>i);if(state.lastCategory!==null&&pool.length>1)pool=pool.filter(i=>i!==state.lastCategory);const i=pool[Math.floor(Math.random()*pool.length)];state.lastCategory=i;return i}
function spinWheel(){const btn=document.getElementById("spinBtn");if(btn.disabled)return;btn.disabled=true;const idx=chooseCategory();const segment=360/7,target=360-(idx*segment+segment/2);state.rotation+=1440+target-(state.rotation%360);document.getElementById("wheel").style.transform="rotate("+state.rotation+"deg)";beep(420,.18);setTimeout(()=>{const c=categories[idx];state.currentCategory=c.id;state.rounds++;save();document.getElementById("selectedArea").innerHTML='<div class="selected-icon">'+c.icon+'</div><h2>'+c.name.toUpperCase()+'</h2><p>Kategori dipilih!</p><button class="primary" onclick="openRandomSituation()">📜 LIHAT CABARAN</button>';beep(920,.16);burst()},4650)}
function burst(){showToast("✨ Kategori dipilih!")}
function openRandomSituation(){const arr=data[state.currentCategory];let idx=Math.floor(Math.random()*arr.length);const key=state.currentCategory+":"+idx;if(arr.length>1&&state.played.includes(key)){idx=(idx+1)%arr.length}state.currentIndex=idx;state.played.push(state.currentCategory+":"+idx);state.played=state.played.slice(-20);save();renderSituation()}
function current(){return data[state.currentCategory][state.currentIndex]}
function easyVersion(x){if(state.mode!=="easy")return x;if(x.levels)return x;const copy={...x};if(copy.open&&!copy.o){copy.o=["😡 Bergaduh","🤝 Berbincang / bergilir","🙈 Abaikan masalah"];copy.a=1;copy.f="Bagus! Pilihan ini membantu semua orang.";copy.open=false}return copy}
function renderSituation(){const c=categories.find(x=>x.id===state.currentCategory),x=easyVersion(current());if(state.mode==="kbat"&&c.id!=="kbat"&&!x.levels){x.open=true;x.o=null;x.q=x.q+" Berikan alasan dan ramalkan kesannya."}
let content='<div class="card-layout"><div class="panel"><div class="scene">'+c.icon+'</div><span class="pill">'+c.icon+" "+c.name+'</span><p class="situation-text">'+x.s+'</p><button class="secondary" onclick="speakCurrent()">🔊 BACA SOALAN</button></div><div class="panel"><h2>'+x.q+'</h2>';
if(x.levels)content+=renderLevels(x);
else if(x.o)content+='<div class="option-grid">'+x.o.map((o,i)=>'<button class="option" onclick="answerOption('+i+')">'+String.fromCharCode(65+i)+". "+o+"</button>").join("")+'</div><div id="feedback"></div>';
else content+=renderOpen(x);
content+='<div class="action-row"><button class="secondary" onclick="toggleFrame()">📝 BANTU SAYA MENJAWAB</button><button class="secondary" onclick="toggleAnswer()">💡 LIHAT CADANGAN JAWAPAN</button></div><div id="frameBox" class="help-box hidden">'+sentenceFrames()+'</div><div id="answerBox" class="help-box hidden"><b>Cadangan jawapan:</b><p>'+x.answer+'</p></div></div></div>';
render(content,"situation")}
function sentenceFrames(){return '<div class="sentence">Saya memilih __________ kerana __________.</div><div class="sentence">Jika mereka tidak bertoleransi, __________.</div><div class="sentence">Mereka sepatutnya __________ supaya __________.</div>'+(state.mode==="kbat"?'<div class="sentence">Saya mencadangkan __________ dan __________. Saya memilih __________ sebagai penyelesaian terbaik kerana __________.</div>':"")}
function renderOpen(x){return '<textarea id="openInput" class="open-answer" placeholder="Tulis jawapan kamu di sini…"></textarea>'+(x.frame?'<div class="sentence">'+x.frame+'</div>':"")+'<div class="action-row"><button class="primary" onclick="submitOpen()">✅ HANTAR JAWAPAN</button></div><div id="feedback"></div>'}
function answerOption(i){const x=easyVersion(current()),ok=i===x.a;document.querySelectorAll(".option").forEach((b,j)=>{b.classList.toggle("chosen",j===i);b.classList.toggle("correct",ok&&j===i)});const f=document.getElementById("feedback");if(ok){f.innerHTML='<div class="feedback"><strong>🌟 Betul! Ini menunjukkan sikap toleransi.</strong><p>'+(x.f||"Bagus! Kamu memilih tindakan yang membantu semua orang.")+'</p>'+nextButtons(1)+'</div>';reward(1);checkBadges()}else f.innerHTML='<div class="feedback think"><strong>💡 Cuba fikir semula.</strong><p>Apakah tindakan yang membantu semua orang?</p></div>'}
function submitOpen(){const v=document.getElementById("openInput").value.trim();if(!v){showToast("Tulis jawapan dahulu.");return}document.getElementById("feedback").innerHTML='<div class="feedback"><strong>💡 Jawapan sudah direkodkan.</strong><p>Bincangkan alasan kamu bersama guru atau rakan. Tekan “Lihat Cadangan Jawapan” untuk membuat perbandingan.</p>'+nextButtons(state.mode==="kbat"?2:1)+'</div>';reward(state.mode==="kbat"?2:1);checkBadges()}
function nextButtons(n){return '<div class="action-row"><button class="primary" onclick="nextRound()">🎡 PUTAR LAGI</button><button class="secondary" onclick="renderReflection()">💗 REFLEKSI</button></div>'}
function reward(n){state.stars+=n;state.answered++;save();beep(1040,.16);showToast("⭐ +"+n+" Bintang Toleransi");if(state.stars>=TARGET_STARS)setTimeout(renderWin,500)}
function renderLevels(x){return '<div class="levels">'+x.levels.map((l,i)=>'<button class="level '+(state.levelDone[i]?"done":"")+'" onclick="openLevel('+i+')">'+l[0]+'<br><span class="small">'+(l[3]===2?"⭐⭐":"⭐")+'</span></button>').join("")+'</div><div id="levelArea" class="help-box"><p>Pilih satu tahap cabaran.</p></div>'}
function openLevel(i){const x=current(),l=x.levels[i];document.getElementById("levelArea").innerHTML='<h3>'+l[0]+'</h3><p class="question">'+l[1]+'</p><textarea id="levelInput" class="open-answer" placeholder="Jawapan…"></textarea><div class="action-row"><button class="primary" onclick="submitLevel('+i+')">Hantar</button><button class="secondary" onclick="document.getElementById(\'levelArea\').insertAdjacentHTML(\'beforeend\',\'<div class=&quot;feedback&quot;><b>Cadangan:</b> '+l[2].replace(/'/g,"&#39;")+'</div>\')">💡 Cadangan</button></div>'}
function submitLevel(i){const input=document.getElementById("levelInput");if(!input.value.trim()){showToast("Tulis jawapan dahulu.");return}if(!state.levelDone[i]){const pts=current().levels[i][3];state.levelDone[i]=true;reward(pts)}if(Object.keys(state.levelDone).filter(k=>state.levelDone[k]).length>=4){document.getElementById("levelArea").innerHTML='<div class="feedback"><strong>🏆 Empat tahap selesai!</strong><p>Kamu berjaya mengenal pasti masalah, mencadangkan tindakan, meramalkan kesan dan memberi justifikasi.</p><button class="primary" onclick="nextRound()">🎡 PUTAR LAGI</button></div>'}else openLevel(i)}
function toggleFrame(){document.getElementById("frameBox")?.classList.toggle("hidden")}
function toggleAnswer(){document.getElementById("answerBox")?.classList.toggle("hidden")}
function nextRound(){state.levelDone={};save();renderWheel()}
function renderBadges(){const defs=[["listener","⭐ Pendengar Baik"],["solver","🤝 Penyelesai Konflik"],["kbat","💬 Bijak Berbincang"],["harmony","🏆 Pasukan Harmoni"]];return '<h3>✨ Lencana</h3><div class="badges">'+defs.map(d=>'<div class="badge '+(state.badges.includes(d[0])?"earned":"")+'">'+d[1]+'</div>').join("")+'</div>'}
function checkBadges(){if(state.currentCategory==="pendapat"&&!state.badges.includes("listener"))state.badges.push("listener");if(state.answered>=3&&!state.badges.includes("solver"))state.badges.push("solver");if((state.mode==="kbat"||state.currentCategory==="kbat")&&!state.badges.includes("kbat"))state.badges.push("kbat");if(state.stars>=TARGET_STARS&&!state.badges.includes("harmony"))state.badges.push("harmony");save()}
function renderWin(){if(!state.badges.includes("harmony"))state.badges.push("harmony");save();render('<div class="panel center"><div class="confetti">🎉 ⭐ 🤝 🌈 ⭐ 🎉</div><h1 class="big">🏆 TAHNIAH!</h1><h2>ANDA TELAH MENJADI</h2><h1>🌈 PASUKAN HARMONI</h1><p class="subtitle">Kamu berjaya menunjukkan cara berbincang, menghormati dan bertolak ansur!</p><div class="stars">⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐</div><div class="action-row" style="justify-content:center"><button class="primary" onclick="restartKeepMode()">🎡 MAIN LAGI</button><button class="secondary" onclick="renderReflection()">💗 REFLEKSI AKHIR</button></div></div>',"win");beep(1200,.3)}
function renderReflection(){render('<div class="panel center"><span class="pill">💗 Refleksi Akhir</span><h1>Apakah satu perkara yang perlu kita lakukan apabila berbeza pendapat?</h1><p>Pilih semua tindakan positif.</p><div class="reflection-options"><button class="reflect" data-good="1" onclick="reflect(this)">🤝 Berbincang</button><button class="reflect" data-good="1" onclick="reflect(this)">❤️ Menghormati</button><button class="reflect" data-good="1" onclick="reflect(this)">🕊️ Bertolak ansur</button><button class="reflect" data-good="0" onclick="reflect(this)">😡 Bergaduh</button></div><div id="reflectionFeedback"></div></div>',"reflection")}
function reflect(btn){btn.classList.toggle("selected");const chosen=[...document.querySelectorAll(".reflect.selected")],good=chosen.filter(b=>b.dataset.good==="1").length,bad=chosen.some(b=>b.dataset.good==="0");if(good===3&&!bad)document.getElementById("reflectionFeedback").innerHTML='<div class="feedback"><h2>🌟 TEPAT!</h2><p>Berbincang, menghormati dan bertolak ansur membantu kita hidup dengan aman.</p><h2>🤝 “BERBINCANG, MENGHORMATI DAN BERTOLAK ANSUR!”</h2><button class="primary" onclick="renderHome()">🏠 Menu Utama</button></div>'}
function restartKeepMode(){const m=state.mode,s=state.sound;state={stars:0,rounds:0,mode:m,sound:s,lastCategory:null,played:[],answered:0,badges:[],screen:"wheel",currentCategory:null,currentIndex:0,rotation:0,answerVisible:false,levelDone:{}};save();renderWheel()}
function speakText(t){if(!("speechSynthesis" in window)){showToast("Fungsi bacaan tidak disokong pelayar ini.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="ms-MY";u.rate=.9;speechSynthesis.speak(u)}
function speakCurrent(){const x=current();speakText(x.s+" "+x.q)}
function openTeacher(){const m=document.getElementById("teacherModal");m.classList.add("open");m.setAttribute("aria-hidden","false");const csel=document.getElementById("teacherCategory");csel.innerHTML=categories.map(c=>'<option value="'+c.id+'" '+(c.id===state.currentCategory?"selected":"")+'>'+c.icon+" "+c.name+"</option>").join("");syncTeacherSituations()}
function syncTeacherSituations(){const id=document.getElementById("teacherCategory").value,sel=document.getElementById("teacherSituation");sel.innerHTML=data[id].map((x,i)=>'<option value="'+i+'">'+(i+1)+". "+x.s.slice(0,62)+"…</option>").join("")}
function closeTeacher(){const m=document.getElementById("teacherModal");m.classList.remove("open");m.setAttribute("aria-hidden","true")}
function teacherOpen(){state.currentCategory=document.getElementById("teacherCategory").value;state.currentIndex=Number(document.getElementById("teacherSituation").value);state.levelDone={};save();closeTeacher();renderSituation()}
function teacherShowAnswer(){const id=document.getElementById("teacherCategory").value,i=Number(document.getElementById("teacherSituation").value),box=document.getElementById("teacherAnswer");box.innerHTML="<b>Cadangan jawapan:</b><p>"+data[id][i].answer+"</p>";box.classList.toggle("hidden")}
document.getElementById("homeBtn").onclick=renderHome;
document.getElementById("soundBtn").onclick=()=>{state.sound=!state.sound;document.getElementById("soundBtn").textContent=state.sound?"🔊":"🔇";save()};
document.getElementById("teacherBtn").onclick=openTeacher;document.getElementById("closeTeacher").onclick=closeTeacher;
document.getElementById("teacherCategory").onchange=syncTeacherSituations;document.getElementById("teacherOpen").onclick=teacherOpen;
document.getElementById("teacherSpin").onclick=()=>{closeTeacher();renderWheel();setTimeout(spinWheel,250)};
document.getElementById("teacherAddStar").onclick=()=>{state.stars++;save();showToast("⭐ Bintang ditambah")};
document.getElementById("teacherMinusStar").onclick=()=>{state.stars=Math.max(0,state.stars-1);save();showToast("Bintang ditolak")};
document.getElementById("teacherAnswerToggle").onclick=teacherShowAnswer;
document.getElementById("teacherEasy").onclick=()=>{setMode("easy");closeTeacher()};
document.getElementById("teacherKbat").onclick=()=>{setMode("kbat");closeTeacher()};
document.getElementById("teacherSound").onclick=()=>{state.sound=!state.sound;document.getElementById("soundBtn").textContent=state.sound?"🔊":"🔇";save()};
document.getElementById("teacherReset").onclick=()=>{if(confirm("Padam semua progres permainan?")){localStorage.removeItem("roda-toleransi-v1");location.reload()}};
document.getElementById("teacherModal").addEventListener("click",e=>{if(e.target.id==="teacherModal")closeTeacher()});
load();document.getElementById("soundBtn").textContent=state.sound?"🔊":"🔇";renderHome();
